group_list:
    developer: {}
    tester: {}
    engineer: {}
    systems-analyst: {}

user_list:
    developer:
        {
            comment: "developer",
            groups: ["developer", "docker"],
            shell: "/bin/bash",
            home: "/home/developer/",
        }
    tester:
        {
            comment: "tester",
            groups: ["tester", "docker"],
            shell: "/bin/bash",
            home: "/home/tester/",
        }
    engineer:
        {
            comment: "engineer",
            groups: ["engineer", "docker"],
            shell: "/bin/bash",
            home: "/home/engineer/",
        }
    systems-analyst:
        {
            comment: "systems-analyst",
            groups: ["systems-analyst", "docker"],
            shell: "/bin/bash",
            home: "/home/systems-analyst/",
        }
