default:
  image:
    name: hashicorp/terraform
    entrypoint: [""]
  timeout: 15 minutes
  cache:
    - key: $CI_PIPELINE_ID-terraform-cache
      paths:
        - ./terraform/environments/${TF_ENV}/${TF_STATE}/.terraform/
        - ./terraform/environments/${TF_ENV}/${TF_STATE}/.terraform.lock.hcl

variables:
  STATE_FILENAME: ${TF_ENV}-${TF_STATE}
  TF_ADDRESS: "https://gitlab.hr-link.ru/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${STATE_FILENAME}"
  ANSIBLE_HOST_KEY_CHECKING: "False"

stages:
  - format
  - init
  - plan
  - apply
  - destroy

format:
  stage: format
  rules:
    - if: $TF_ENV && $TF_STATE
      when: always
  script:
    - terraform -chdir="./terraform/environments/${TF_ENV}/${TF_STATE}" fmt
  cache: []

download_provider:
  stage: init
  rules:
    - if: $TF_ENV && $TF_STATE
      when: always
  script:
    - cp ./terraform/.terraformrc ~/.terraformrc
    - terraform -chdir="./terraform/environments/${TF_ENV}/${TF_STATE}" init
      -backend-config=address=${TF_ADDRESS}
      -backend-config=lock_address=${TF_ADDRESS}/lock
      -backend-config=unlock_address=${TF_ADDRESS}/lock
      -backend-config=username=${TF_USERNAME}
      -backend-config=password=${TF_PASSWORD}
      -backend-config=lock_method=POST
      -backend-config=unlock_method=DELETE
      -backend-config=retry_wait_min=5

plan:
  stage: plan
  rules:
    - if: $TF_ENV && $TF_STATE
      when: always
  script:
    - terraform -chdir="./terraform/environments/$TF_ENV/$TF_STATE" plan
  artifacts:
    name: "${CI_JOB_NAME}-${CI_JOB_ID}"

apply_configuration: 
  stage: apply
  rules:
    - if: $TF_ENV && $TF_STATE
      when: always
  script:
    - terraform -chdir="./terraform/environments/$TF_ENV/$TF_STATE" apply -auto-approve
  artifacts:
    name: "${CI_JOB_NAME}-${CI_JOB_ID}"

destroy: 
  stage: destroy
  rules:
    - if: $TF_ENV && $TF_STATE && $DESTROY
      when: manual
  script:
    - terraform -chdir="./terraform/environments/$TF_ENV/$TF_STATE" destroy -auto-approve
  artifacts:
    name: "${CI_JOB_NAME}-${CI_JOB_ID}"
