- name: conf get
  include_vars:
      file: ../conf/conf.json
      name: conf

- import_tasks: configure-gitlab-runner.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('gitlab-runner'))
