# создание групп
- name: create group
  ansible.builtin.group:
      name: "{{ item }}"
      state: present
  loop: "{{ group_list | default([]) }}"

# создание пользователей
- name: create user
  ansible.builtin.user:
      name: "{{ item.key }}"
      comment: "{{ item.value.comment }}"
      groups: "{{ item.value.groups }}"
      shell: "{{ item.value.shell }}"
      home: "{{ item.value.home }}"
      create_home: "yes"
  loop: "{{ user_list | default({}) | dict2items }}"

# # TODO пока нет необходимости
# # добавление публичных ssh ключей
# - name: get authorized keys token from file
#   ansible.posix.authorized_key:
#       user: "{{ item.key }}"
#       state: present
#       exclusive: true
#       key: "{{ lookup('file', '{{ item.key }}.pub')}}"
#   loop: "{{ user_list | default({}) | dict2items }}"
