- name: install postgresql
  apt:
    name: postgresql
    state: latest
    #   update_cache: true

- name: stop postgresql service
  service:
    name: postgresql
    state: stopped
    enabled: no
