- name: install reverse packages
  apt:
      name: "{{ app_list_reverse_nginx | default([]) }}"
      state: present

- name: nginx config copy
  ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/conf.d/ansible.conf
#   tags:
#       - reverse
