- import_tasks: install-packages-ubuntu.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|regress|staging|onprem|prod|runner'))

- import_tasks: mount-disk.yaml
  when: ansible_facts['distribution'] in ubuntu_list and secondary_disk_mount_point != '' and (inventory_hostname | regex_search('dev|test|devops|staging|onprem|prod'))

- import_tasks: mount-filesystem.yaml
  when: ansible_facts['distribution'] in ubuntu_list and filesystem_name != '' and (inventory_hostname | regex_search('dev|test|devops|staging'))

# TODO reverse_nginx_hostname - переменная из defaults/main.yaml
- import_tasks: install-nginx.yaml
  when: ansible_facts['distribution'] in ubuntu_list and inventory_hostname == reverse_nginx_hostname

- import_tasks: install-docker.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|staging|onprem|prod|runner'))

- import_tasks: install-ftp-server.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|staging'))

- import_tasks: install-postgresql.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|staging'))

- import_tasks: configure-jenkins-agent.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|staging'))
