- name: conf get
  include_vars:
      file: ../conf/conf.json
      name: conf

- import_tasks: install-packages-ubuntu.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|regress|staging|onprem|sales|prod|runner|infra|mock'))

- import_tasks: mount-disk.yaml
  when: ansible_facts['distribution'] in ubuntu_list and secondary_disk_mount_point != '' and (inventory_hostname | regex_search('dev|test|devops|staging|onprem|sales|prod|infra|mock')) and not (inventory_hostname | regex_search('runner'))

- import_tasks: mount-filesystem.yaml
  when: ansible_facts['distribution'] in ubuntu_list and filesystem_name != '' and (inventory_hostname | regex_search('dev|test|devops|staging')) and not (inventory_hostname | regex_search('runner'))

# # TODO nginx_hostname_mask - переменная из defaults/main.yaml
# - import_tasks: install-nginx.yaml
#   when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search(nginx_hostname_mask))

- import_tasks: install-docker.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|staging|onprem|sales|prod|runner|infra|mock'))

- import_tasks: install-ftp-server.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|staging')) and not (inventory_hostname | regex_search('runner'))

- import_tasks: install-postgresql.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|staging')) and not (inventory_hostname | regex_search('runner'))

- import_tasks: configure-jenkins-agent.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|devops|staging')) and not (inventory_hostname | regex_search('runner'))
