- import_tasks: install-packages-ubuntu.yaml
  when: ansible_facts['distribution'] in ubuntu_list

- import_tasks: install-docker.yaml
  when: ansible_facts['distribution'] in ubuntu_list

- import_tasks: add-pubkeys.yaml

- import_tasks: copy-files.yaml
