- import_tasks: create-users.yaml
  when: ansible_facts['distribution'] in ubuntu_list

- import_tasks: install-packages-ubuntu.yaml
  when: ansible_facts['distribution'] in ubuntu_list

- import_tasks: mount-disk.yaml
  when: ansible_facts['distribution'] in ubuntu_list and secondary_disk_mount_point != ''

- import_tasks: mount-filesystem.yaml
  when: ansible_facts['distribution'] in ubuntu_list and filesystem_name != ''

# TODO reverse_nginx_hostname - переменная из defaults/main.yaml
- import_tasks: install-nginx.yaml
  when: ansible_facts['distribution'] in ubuntu_list and inventory_hostname == reverse_nginx_hostname

- import_tasks: install-docker.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|regress|staging'))

- import_tasks: configure-jenkins-agent.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('dev|test|regress|staging'))
