- import_tasks: wait-for-connection.yaml

- import_tasks: install-packages-ubuntu.yaml
  when: ansible_facts['distribution'] in ubuntu_list

- import_tasks: install-docker.yaml
  when: ansible_facts['distribution'] in ubuntu_list

# TODO условие временное
- import_tasks: install-nginx.yaml
  when: inventory_hostname == "app-trf"

- import_tasks: add-pubkeys.yaml

- import_tasks: copy-files.yaml
