# - name: check if /dev/vdb1 is in /etc/fstab
#   ansible.builtin.shell: grep -q "/dev/vdb1" /etc/fstab
#   register: fstab_check
# #   failed_when: false

- name: check if /dev/vdb1 is in /etc/fstab
  ansible.builtin.command: grep -q '/dev/vdb1' /etc/fstab
  register: fstab_check
  ignore_errors: true

- name: perform disk setup if /dev/vdb1 is not in /etc/fstab
  block:
      - name: perform disk
        ansible.builtin.parted:
            device: /dev/vdb
            number: 1
            state: present
            align: optimal
            part_end: 100%
  when: not fstab_check.stdout

- name: create ext4 filesystem on /dev/vdb1
  block:
      - name: create ext4 filesystem
        ansible.builtin.filesystem:
            fstype: ext4
            dev: /dev/vdb1
  when: not fstab_check.stdout

- name: create mount point
  block:
      - name: create mount point
        ansible.builtin.file:
            path: /mnt/vdb1
            state: directory
  when: not fstab_check.stdout

- name: mount /dev/vdb1 to /mnt/vdb1
  block:
      - name: mount /dev/vdb1 to /mnt/vdb1
        ansible.builtin.mount:
            src: /dev/vdb1
            path: /mnt/vdb1
            fstype: ext4
            state: mounted
            opts: defaults,nofail
  when: not fstab_check.stdout
# - name: add entry to /etc/fstab
#   block:
#       - name: add entry to /etc/fstab
#         ansible.builtin.lineinfile:
#             path: /etc/fstab
#             line: "UUID={{ disk_uuid }} /mnt/vdb1 ext4 defaults 0 2"
#             create: yes
#   when: not fstab_check.stdout
