- name: check if filesystem is in /etc/fstab
  ansible.builtin.command: grep -q '{{ filesystem_name }}' /etc/fstab
  register: fstab_check
  ignore_errors: true

- name: filesystem directory create
  block:
      - name: filesystem directory create
        ansible.builtin.file:
            path: "/mnt/{{ filesystem_name }}"
            state: directory
            mode: 0755
  when: not fstab_check.stdout

- name: filesystem mount
  block:
      - name: filesystem directory create
        ansible.builtin.mount:
            src: "{{ filesystem_name }}"
            path: "/mnt/{{ filesystem_name }}"
            fstype: virtiofs
            opts: defaults,nofail
            state: mounted
            #   fstab: yes
  when: not fstab_check.stdout

# # в таске выше добавление происходит автоматически
# - name: filesystem mount add to /etc/fstab
#   ansible.builtin.lineinfile:
#       path: /etc/fstab
#       line: "{{ filesystem_name }} /mnt/{{ filesystem_name }} virtiofs rw 0 0"
#       create: yes
#       state: present
