- name: filesystem directory create
  ansible.builtin.file:
      path: "/mnt/{{ filesystem_name }}"
      state: directory
      mode: 0755

- name: filesystem mount
  ansible.builtin.mount:
      src: "{{ filesystem_name }}"
      path: "/mnt/{{ filesystem_name }}"
      fstype: virtiofs
      opts: defaults
      state: mounted

# - name: filesystem mount add to /etc/fstab
#   ansible.builtin.lineinfile:
#       path: /etc/fstab
#       line: "{{ filesystem_name }} /mnt/{{ filesystem_name }} virtiofs rw 0 0"
#       create: yes
#       state: present
