# TODO в этом виде таймаут не работает
# ansible пытается подключиться к серверу не проверяя проходит ли вообще подключение
- name: wait for server SSH connection
  wait_for_connection:
      delay: 10
      timeout: 300
