# системные пользователи
group_list_system:
    service: { gid: 1186 }

user_list_system:
    service:
        {
            comment: "service",
            groups: ["service", "docker", "jenkins"],
            shell: "/bin/bash",
            home: "/home/service/",
            uid: 1186,
        }

user_list_service: "{{ conf.users_service }}"
