- import_tasks: create-users.yaml
  when: ansible_facts['distribution'] in ubuntu_list

- import_tasks: create-users-external-kaspersky.yaml
  when: ansible_facts['distribution'] in ubuntu_list and (inventory_hostname | regex_search('kaspersky'))
