- name: find home directories
  ansible.builtin.find:
      paths: /home
      file_type: directory
  register: home_directories_bash

- name: add .bash_aliases for managed users
  ansible.builtin.template:
      src: bash_aliases.j2
      dest: "{{ item.path }}/.bash_aliases"
      mode: "0644"
      owner: "{{ item.path | basename }}"
      group: "{{ item.path | basename }}"
  loop: "{{ home_directories_bash.files }}"

- name: add .bash_profile for managed users
  ansible.builtin.template:
      src: bash_profile.j2
      dest: "{{ item.path }}/.bash_profile"
      mode: "0644"
      owner: "{{ item.path | basename }}"
      group: "{{ item.path | basename }}"
  loop: "{{ home_directories_bash.files }}"

# # TODO ниже варианты в которых не получилось сделать так чтобы строка не добавлялась повторно,
# # когда она уже добавлялась ранее, пока пусть побудут здесь
# - name: add paths to .bashrc
#   ansible.builtin.lineinfile:
#       path: "{{ item.path }}/.bashrc"
#       line: |

#           {% for path in app_paths %}
#           export PATH="$PATH:{{ path }}"
#           {% endfor %}
#       create: true
#       state: present
#   loop: "{{ home_directories_bash.files }}"

# - name: form app paths content
#   ansible.builtin.set_fact:
#       app_paths_content: |

#           {% for path in app_paths %}
#           export PATH="$PATH:{{ path }}"
#           {% endfor %}

# - name: add paths to .bashrc
#   ansible.builtin.lineinfile:
#       path: "{{ item.path }}/.bashrc"
#       line: "{{ app_paths_content }}"
#       insertafter: "^    . /etc/bash_completion\n  fi\nfi$"
#       create: true
#       state: present
#   loop: "{{ home_directories_bash.files }}"
