# TODO в этом виде таймаут не работает, т.к. раньше происходит попытка выполнить таску gather_facts, ещё до готовности сервера
- name: wait for server SSH connection
  wait_for_connection:
      delay: 10
      timeout: 300
