- name: standard server playbook
  hosts: common

  # # TODO возможно получится разобраться с кастомизацией gather_facts
  # gather_facts: false
  # tasks:
  #   - name: Gather facts with timeout and retries
  #     setup:
  #       register: facts_result
  #       retries: 6  # количество попыток
  #       delay: 10   # задержка между попытками (в секундах)
  #       until: facts_result is not failed or facts_result is defined

  become: true
  force_handlers: true
  vars:
    server_role_enabled: "{{ 'server' in ansible_run_tags }}"
    users_role_enabled: "{{ 'users' in ansible_run_tags }}"
    app_role_enabled: "{{ 'app' in ansible_run_tags }}"
    one_time_role_enabled: "{{ 'one-time' in ansible_run_tags }}" 
  roles:
    # - role: system
    #   tags: [ system ]
    - role: configure-server
      tags: [ server ]
    - role: configure-users
      tags: [ users ]
    - role: one-time-actions
      when: one_time_role_enabled
      tags: [ one-time ]