- name: standart server playbook
  hosts: common

  gather_facts: false
  tasks:
    - name: Gather facts with timeout and retries
      block:
        - name: Gather facts
          setup:
          register: facts
        - name: Check if facts are gathered successfully
          assert:
            that: facts.facts != null
            success_msg: "Facts are gathered successfully"
            fail_msg: "Facts gathering failed"
      retries: 6  # Количество попыток
      delay: 10    # Задержка между попытками (в секундах)
      until: facts is defined and facts.facts != null

  become: true
  roles:
    # - system
    - configure-server
