- name: standard server playbook
  hosts: mock
  become: true
  force_handlers: true
  vars:
    server_role_enabled: "{{ 'server' in ansible_run_tags }}"
    users_role_enabled: "{{ 'users' in ansible_run_tags }}"
    app_role_enabled: "{{ 'app' in ansible_run_tags }}"
    one_time_role_enabled: "{{ 'one-time' in ansible_run_tags }}" 
  roles:
    - role: configure-server
      tags: [ server ]
    - role: configure-users
      tags: [ users ]
    - role: one-time-actions
      when: one_time_role_enabled
      tags: [ one-time ]