group_list:
    - jenkins
    - tester
    - engineer

user_list:
    jenkins:
        {
            comment: "jenkins",
            groups: ["jenkins"],
            shell: "/bin/bash",
            home: "/home/jenkins/",
        }
    tester:
        {
            comment: "tester",
            groups: ["tester"],
            shell: "/bin/bash",
            home: "/home/tester/",
        }
    engineer:
        {
            comment: "engineer",
            groups: ["engineer"],
            shell: "/bin/bash",
            home: "/home/engineer/",
        }
