passwords_salt: "{{ lookup('env', 'PASSWORDS_SALT') | default('default_salt') }}"
user_passwords: "{{ lookup('env', 'USER_PASSWORDS', default='{}') }}"

user_list_jenkins: "{{ lookup('env', 'USERS_JENKINS', default='').split(',') }}"
user_list_docker: "{{ lookup('env', 'USERS_DOCKER', default='').split(',') }}"

docker_hub_address: docker.hr-link.ru
docker_hub_user: "{{ lookup('env', 'DOCKER_HUB_USER', default='') }}"
docker_hub_password: "{{ lookup('env', 'DOCKER_HUB_PASSWORD', default='') }}"

bash_aliases:
    cdd: "cd /var/hrlink/"
    cdv: "cd /var/hrlink/vms/"
    cdw: "cd /var/hrlink/working-data/"
    cdc: "cd /var/hrlink/conf/"
    cdf: "cd /mnt/"

app_paths:
    # - /var/hrlink/vms/
    - /var/hrlink/vms/scripts/
